import Controller from '@ember/controller';
import {
  inject as service
} from '@ember/service';
import $ from 'jquery';

export default Controller.extend({
  ajax: service(),
  storage: service(),
  notification: service('notification-messages'),
  migratingFrom: ['Tally', 'QuickBooks', 'Xero'],
  orgList: [],
  totalList:[],
  auth: null,
  orgId: null,
  orgName: null,
  prevOrg: null,
  toggled: false,
  proceedToFileUploader: false,
  setprevOrg(migratingFrom) {
    this.set('prevOrg', migratingFrom.highlighted);
  },
  setorg(organization) {
    if (organization.highlighted !== undefined) {
      let orgString = organization.highlighted.split(" ");
      this.set('org',orgString[0]+" "+orgString[1]);
      this.set('orgId', orgString[0]);
      this.set('orgName', orgString[1]);
    }
  },
  actions: {
    populateAuth() {
      this.set('auth', $("#authValue").text())
      $("#authToken").val($("#authValue").text());
      this.send('postAuth');

    },
    postAuth() {
      if (this.get('auth') !== null&& this.get('auth') !== undefined) {
        if ($("#authToken").val().length === 32)
          {
            this.set('auth', $("#authToken").val());
            this.set('orgId',"");
            this.set('prevOrg',"");
            this.set('org',"");
            $("#file").val("");
            $(".file-path").val("");
          }

        $('.right').show();
        var _this = this;

        this.get('ajax').request('http://localhost:8080/Migration/OrganizationList', {
          method: "POST",
          headers: {
            'Access-Control-Allow-Origin': '*'
          },
          data: {
            "authtoken": this.get('auth')
          },

          success: function(res) {
            _this.set('orgId',"");
            _this.set('prevOrg',"");
            _this.set('org',"");
            _this.set('totalList',res)
            _this.set('orgList', []);
            Object.entries(res).forEach(
              ([key, value]) => _this.get('orgList').pushObject(key + " " + value.organization_name)
            );
            $('.right').hide();
            _this.get('notification').success('Authentication successful', {
              autoClear: true,
              clearDuration: 1200
            });
          },
          error: function(err) {
             $('.right').hide();
            _this.get('notification').error(err.statusText, {
              autoClear: true,
              clearDuration: 1200
            });

          }

        });
      } else if (this.get('auth').length > 32 || this.get('auth').length < 32) {
        this.set('orgList', []);
        // this.send('validateForm');
      }
    },
    submit() {

      if (!this.get('proceedToFileUploader')) {
        this.send('validateForm');
      } else {
        let file = $("#file");
        let formData = new FormData();
        formData.append("orgId",this.get('orgId'));
        formData.append("file", file);
        $("#form").submit();
      }
    },
    validateForm() {
      let orgId=this.get('orgId');
      let orgList=this.get('totalList');

      if (this.get('auth') === "" || this.get('auth') === null || this.get('auth') === undefined || this.get('auth').length !==32) {
        this.get('notification').error('Invalid AuthToken', {
          autoClear: true,
          clearDuration: 1200
        });
        return false;
      }

      if (this.get('orgId') === "" || this.get('orgId') === null || this.get('orgId') === undefined) {
          this.get('notification').error('Please choose your Organization', {
          autoClear: true,
          clearDuration: 1200
        });
        return false;
      }
      // if (!(orgList[orgId].is_active)) {
      //     this.get('notification').error(`Organization's user is not active`, {
      //     autoClear: true,
      //     clearDuration: 1200
      //   });
      //   return false;
      // }
      // if (!(orgList[orgId].is_trial_expired)) {
      //     this.get('notification').error('Organization trial expired', {
      //     autoClear: true,
      //     clearDuration: 1200
      //   });
      //   return false;
      // }
      // if (!(orgList[orgId].is_admin)) {
      //     this.get('notification').error('AuthToken must be generated by admin', {
      //     autoClear: true,
      //     clearDuration: 1200
      //   });
      //   return false;
      // }
      // if (!(orgList[orgId].is_indian_edition)) {
      //     this.get('notification').error('Please choose a Indian edition Organization', {
      //     autoClear: true,
      //     clearDuration: 1200
      //   });
      //   return false;
      // }

     if (this.get('prevOrg') === "" || this.get('prevOrg') === null || this.get('prevOrg') === undefined) {
        this.get('notification').error('Migration From is Empty', {
          autoClear: true,
          clearDuration: 1200
        });
        return false;
      }
      if (!this.get('toggled')) {

        let file = $("#file").val();
        if (file === "") {
          this.get('notification').error('Please upload a file', {
            autoClear: true,
            clearDuration: 1200
          });
          return false;
        }
      }
      this.get('storage').set('auth', this.get('auth'));
      this.get('storage').set('orgId', this.get('orgId'));
      this.get('storage').set('orgName', this.get('orgName'));
      this.get('storage').set('prevOrg', this.get('prevOrg').toLowerCase());
      this.get('storage').set('isRecentMigration', this.get('toggled'));
      this.set('proceedToFileUploader', true);
      this.send('submit');
    },
  }
});
